#
# _config.yml for heatmap.tv
#

exclude: [ "CNAME", "README.md", "LICENSE.txt", "tmp", "*.sh", "**/*_src*" ]
permalink: /news/:year/:month/:day/:title.html
production_url: https://warpspeed.faithlifenow.com/
title: Heatmap TV
markdown: kramdown
plugins:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

google_analytics_id: "UA-328425-42"
google_validation: "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"
bing_validation: "E90DBA4A9D3D37F1056E64E5604A7A0D"
google_maps_api_key: "AIzaSyAG40aREzio2rEz1dkB_3ABk1fVZpRJQgo"
google_client_id: "53471891795-nfiiv71k9p28f1d6r886r94l9dq0n4m2.apps.googleusercontent.com"
